name: "Script de déploiement"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: "Lancement de Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Récupération de la branche 'state'
        working-directory: .
        run: |
          git fetch origin state || echo "Branche state inexistante"
          git checkout state || git checkout --orphan state

      - name: Restauration du Terraform state
        working-directory: .
        run: |
          if [ -f terraform.tfstate ]; then
            cp terraform.tfstate terraform/terraform.tfstate
          else
            echo "Aucun state existant à restaurer."
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Génération du fichier ZIP pour la Lambda
        working-directory: .
        run: |
          cd lambda
          zip -r lambda.zip index.js
          mv lambda.zip ../terraform/

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false tfplan

      - name: Affichage de l'URL de l'API Gateway
        working-directory: ./terraform
        run: |
          echo "API URL: $(terraform output api_url)"

      - name: Sauvegarde du Terraform state dans 'state'
        working-directory: .
        run: |
          cp terraform/terraform.tfstate terraform.tfstate
          git add terraform.tfstate
          git commit -m "Mise à jour du Terraform state"
          git push origin state